version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: test

    mysql:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: test
